name: CI/CD React

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 13.10
      uses: actions/setup-node@v1
      with:
        node-version: '13.10'

    - name: Run npm install
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_SECRET }}
        port: 21